steps:
  - name: ":docker:"
    plugins:
      docker-compose#v1.5.2:
        build: streetscape
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders

  - wait

  - name: ":eslint:"
    command: "yarn lint"
    plugins:
      docker-compose#v1.5.2:
        run: streetscape
    agents:
      queue: workers

  - name: ":node:"
    command: "yarn test cover && cat coverage/lcov.info | coveralls"
    plugins:
      docker-compose#v1.5.2:
        run: streetscape
    agents:
      queue: workers

  - name: ":chrome:"
    command: "sh /etc/init.d/xvfb && yarn test browser"
    plugins:
      docker-compose#v1.5.2:
        run: streetscape
    agents:
      queue: workers
